### ISSUE TITLE
Trauma dump 

### ISSUE THREAD

**Issue by Relaxtest2024** [TedSinger/blurbcloud#10]
Trauma dump for today…
I finished work 8pm last night - but I spent the rest of time googling your web domain name. And spent the whole rest of time figuring out what is DNS server/router blah blah. I am feeling more and more geeky. 
ChatGPT is awesome! I am learning things so much faster with it. I mean computer science world /AI world is fascinating but it is not useful when it comes to healthcare system. Life science is the domain where people need to understand the arts of materials: the joint universe of physics/chemistry múltiple dimensionally.

I am very disappointed again at the housing in NYC. Most places are tiny and antiquey. I feel suffocated even walking into it. I am moving to Brooklyn or somewhere close to subway but not manhattan. I don’t understand why people can live in a matchbox like that at all. I need to run a side business. I am interested in your blurb.cloud - may acquire it and rerun it on my own. I mean it’s useful. It’s good to pack it into an app. I wish I had time. It’s a very cool business idea I think what blurb.cloud has shown me. I’ll give it a try. ( I don’t want to live in shabby places!!!!!)

Two couples visited my place yesterday as potential lease takers. My place is soooo good that I feel terrible that I am leaving it. ( I don’t even want to live in downtown manhattan unless they fix the subway smell issue). Ideally I’d live in edgewater and rent a dock near midtown and sail to work. Or just buy a boat and live on a boat. And I can sail all the way up Hudson River and fish. 🎣 and have river view. Need to move towards this life.

Ah. I still have many things to say. But I’ll leave it I need to get up and work. I have troubles of getting up. I work much more efficiently later at night. Less anxiety I guess.

boom.💥 have a good weekend

**Comment by totoroclub123** [comment]
Well Yesterday we had happy hour with the whole lab. And my labmates Luka and Andrew both like the idea of blurb.cloud; Luka's family is in fashion industry, leading business partner with Gucci etc in Serbia; I asked him if digital nomads like us can be trend-setter in fashion industry and make QR code cool and also people can interact with each other by QR code printed on fabric. I still think it is a good idea; I sent you a handbag with QR code printed,  -- it is part of the idea. 

Anyways, I am not in a rush. I'll fork this repository first and may outsource this idea to someone that I know sometime later and see how things can go. I have two meetings today. 

Luka is also CS major,this guy finished his master at 23 this year. His motivation is exactly like mine, to create portfolio of work that people can remember him afterwards. Glad that we have Aleks, Luka in the group

**Comment by totoroclub123** [comment]
I didn't find any license under this blurb.cloud thing. 
Just in case I really am making an effort in pushing it into a small business -- I am leaving a message here until one moment later you'll be ready to negotiate your reward from this idea? 
Anyways, it can be a success or not depending on how good my friends are.

**Comment by totoroclub123** [comment]
Okay, more trauma dump from today -- all my prospectus roommates are flaky.. Lizz has to have extra 3 months of medical leave before she can move in with anybody. The columbia female student is flaky, she may not even want to come to columbia for master degree any more. And I am going back to solo mode again. 1b1b it is. Everything in NYC is spinning fast and nobody has any patient towards anyone else...

**Comment by totoroclub123** [comment]
I texted my landlord and asked for one month extension.
This month has been too cutting throat for me. Obviously this whole year has been cutting throat for me.
The world outside campus environment is crazy, chaotic, vibrant, richful but also kaleidoscopic. 
I visited Stony brook a few weeks ago and had dinner with Emily Riehl. Now that I know why campus environment is so good - IT IS GOOD because it is more calm and less enticing. I need to find way back to inner peace.

**Comment by Relaxtest2024** [comment]
Well. Weirdly.
I can just buy an apartment in Manhattan directly- my random idea- that I actually don’t need to throw the money into rental…
Some of them are not actually expensive like 300k-400k.
I wonder why people are not just buying them… 
Interesting
